namespace: cp4aiops

gitops:
  namespaceScoped: false

catalog:
  name: ibm-aiops-catalog
  image: icr.io/cpopen/ibm-aiops-catalog@sha256:fab747229c9b6670c24a7180d010539d01ed07db99aa9f7fa3711e087f4bcf08

subscription:
  name: ibm-aiops-orchestrator
  channel: v4.12

installation:
  name: ibm-cp-aiops
  spec:
    size: large
    storageClass: ocs-storagecluster-cephfs
    storageClassLargeBlock: ocs-storagecluster-ceph-rbd
    topologyModel: application
    license:
      accept: ''
    pakModules:
    - name: aiopsFoundation
      enabled: true
    - name: applicationManager
      enabled: true
    - name: aiManager
      enabled: true
    - name: connection
      enabled: false
    - name: logAnomalyDetection
      enabled: false

monitoring:
  enabled: true
  grafana:
    namespace: monitoring-grafana
    subscription:
      name: monitoring-grafana
      channel: v5
      source: community-operators
      sourceNamespace: openshift-marketplace
    storage:
      size: 2Gi
      storageClass: ""  # Uses default storage class if empty
    oauth:
      image: registry.redhat.io/openshift4/ose-oauth-proxy:v4.14
    prometheus:
      url: https://thanos-querier.openshift-monitoring.svc.cluster.local:9091
