apiVersion: instana.io/v1
kind: InstanaAgent
metadata:
  finalizers:
    - v3.agent.instana.io/finalizer
  name: instana-agent
  namespace: instana-agent
  annotations:
    argocd.argoproj.io/sync-wave: "210"
spec:
  agent:
    pod:
      affinity: {}
      limits:
        cpu: 500m
        memory: 768Mi
      requests:
        cpu: 400m
        memory: 768Mi
    host: {}
    endpointPort: '443'
    downloadKey: {{.Values.instana.key}}
  kubernetes:
    tls: {}
    image: {}
    updateStrategy: {}
    endpointHost: {{.Values.instana.endpointHost}}
    key: {{.Values.instana.key}}
  kubernetes:
    deployment:
      pod: {}
  prometheus:
    remoteWrite: {}
  zone:
    name: {{.Values.instana.clusterName}}
  opentelemetry:
    grpc: {}
    http: {}
  rbac: {}
  k8s_sensor:
    deployment:
      enabled: true
      pod:
        limits:
          cpu: 1000m
          memory: 768Mi
        requests:
          cpu: 500m
          memory: 768Mi
    image: {}
  service: {}
  podSecurityPolicy: {}
  openshift: true
  serviceAccount: {}
  cluster:
    name: {{.Values.instana.clusterName}}