{{- if not .Values.gitops.namespaceScoped}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{.Values.namespace}}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
{{- end }}
---
{{- if .Values.monitoring.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{.Values.monitoringNamespace}}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
{{- end }}